controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true # IMPORTANTE

    # Lista de controladores disponibles
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Configuración del joint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    # Publica el estado de todos los joints del robot
    # No necesita configuración adicional

# Configuración del controlador de posición
arm_position_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - arm_link_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    # Configuración PID
    gains:
      arm_link_joint:
        p: 100.0
        i: 0.01
        d: 10.0

    # Tolerancias
    constraints:
      goal_time: 3.0
      stopped_velocity_tolerance: 0.05
      arm_link_joint:
        trajectory: 0.2
        goal: 0.2
