controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_force_controller:
      type: effort_controllers/JointGroupEffortController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

# Joint state broadcaster configuration
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints: [arm_link_joint]
    interfaces: [position, velocity, effort]

# PRIMARY CONTROLLER: Direct motor force/thrust control
motor_force_controller:
  ros__parameters:
    use_sim_time: true
    joints: [arm_link_joint]
    command_interfaces: [effort]

    # Force limits for propeller (POSITIVE ONLY)
    effort_limits:
      arm_link_joint:
        min: 0.0
        max: 50.0

# BACKUP CONTROLLER: Direct velocity control
velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints: [arm_link_joint]
    command_interfaces: [velocity]

    # Velocity limits
    velocity_limits:
      arm_link_joint:
        min: 0.0
        max: 785.0
