controller_manager:
  ros__parameters:
    update_rate: 250
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: forward_command_controller/ForwardCommandController
      joints: [arm_link_joint]
      interface_name: velocity

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints: [arm_link_joint]
    interfaces: [position, velocity]
    publish_rate: 100.0

velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints: [arm_link_joint]
    interface_name: velocity
